name: Push Event Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v4
      
    - name : Install Packages 
      run : pip install numpy as np
    - run : pip install scipy as sp
    - run : pip install qutip as qt
    - run : pip install joblib
      
    - name : Run tests 
      run : python -m  unittest discover